### ISSUE TITLE
System specific new line character should be asserted in test. Few tests failing on windows env.

### ISSUE THREAD

**Issue by RahulNagekar** [LableOrg/java-maven-junit-helloworld#10]
System specific new line character should be asserted in test. Few tests failing on windows env.

**Comment by RahulNagekar** [comment]
May I work on it? I am trying to understand GitHub would like to contribute for the same :-)

**Comment by jdhoek** [comment]
Hi @RahulNagekar,

Thanks for noticing that bug. I've fixed it in ef2291db9f4ae83bd4c69e0bea1f4b0f8d3e7472.
